### ISSUE TITLE
Error while starting bot

### ISSUE THREAD

**Issue by KaratekHD** [PaulSonOfLars/tgbot#70]
Hello,
I am currently having troubles with setting up Marie.
When trying to start here I get the following Error:
```
2020-01-02 12:39:54,994 - tg_bot - INFO - Not loading: ['translation']
2020-01-02 12:39:54,994 - tg_bot - INFO - Modules to load: ['admin', 'afk', 'antiflood', 'backups', 'bans', 'blacklist', 'cust_filters', 'disable', 'global_bans', 'locks', 'log_channel', 'misc', 'msg_deleting', 'muting', 'notes', 'reporting', 'rss', 'rules', 'sed', 'userinfo', 'users', 'warns', 'welcome']
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jens/tgbot/tg_bot/__main__.py", line 74, in <module>
    imported_module = importlib.import_module("tg_bot.modules." + module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jens/tgbot/tg_bot/modules/backups.py", line 10, in <module>
    from tg_bot.__main__ import DATA_IMPORT
  File "/home/jens/tgbot/tg_bot/__main__.py", line 74, in <module>
    imported_module = importlib.import_module("tg_bot.modules." + module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jens/tgbot/tg_bot/modules/locks.py", line 23, in <module>
    'document': Filters.document & ~Filters.animation,
AttributeError: type object 'Filters' has no attribute 'animation'
```
I saw  #59, but I think this isn't my problem.
What is the problem?
Thanks for your help.

**Comment by PaulSonOfLars** [comment]
You are using the wrong version of the PTB lib.
Install it through `pip3 install - r requirements.txt`.

**Comment by KaratekHD** [comment]
Thank you a lot! This fixed it.
