### ISSUE TITLE
 sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqldbtype Error

### ISSUE THREAD

**Issue by charindith** [PaulSonOfLars/tgbot#86]
my `config.py` is here

```
    OWNER_ID = 9829c10057  # my telegram ID
    OWNER_USERNAME = "charindith"  # my telegram username
    API_KEY = "11846d7265:AAGpXcl1ssssuKNW7rgB8dwh4dddddv9Dg"  # my api key, as provided by the botfather
    SQLALCHEMY_DATABASE_URI = 'sqldbtype://charin:charin@localhost:5432/charin'  # sample db credentials
    MESSAGE_DUMP = '-1012430833035' # some group chat that your bot is a member of
    USE_MESSAGE_DUMP = True
    SUDO_USERS = []  # List of id's for users which have sudo access to the bot.
    LOAD = []
    NO_LOAD = ['translation']
```

I done all the instructions correctly but then this happen
```
root@ip-172-31-44-112:/home/ubuntu/tgbot# python3 -m tg_bot
2020-09-10 19:46:03,627 - tg_bot - INFO - Not loading: ['translation']
2020-09-10 19:46:03,628 - tg_bot - INFO - Modules to load: ['admin', 'afk', 'antiflood', 'backups', 'bans', 'blacklist', 'cust_filters', 'disable', 'global_bans', 'locks', 'log_channel', 'misc', 'msg_deleting', 'muting', 'notes', 'reporting', 'rss', 'rules', 'sed', 'userinfo', 'users', 'warns', 'welcome']
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/tgbot/tg_bot/__main__.py", line 74, in <module>
    imported_module = importlib.import_module("tg_bot.modules." + module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gc
```d_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/tgbot/tg_bot/modules/admin.py", line 12, in <module>
    from tg_bot.modules.disable import DisableAbleCommandHandler
  File "/home/ubuntu/tgbot/tg_bot/modules/disable.py", line 19, in <module>
    from tg_bot.modules.sql import disable_sql as sql
  File "/home/ubuntu/tgbot/tg_bot/modules/sql/__init__.py", line 16, in <module>
    SESSION = start()
  File "/home/ubuntu/tgbot/tg_bot/modules/sql/__init__.py", line 9, in start
    engine = create_engine(DB_URI, client_encoding="utf8")
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 268, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqldbtype

```

**Comment by PaulSonOfLars** [comment]
You've just leaked your token - I recommend you revoke it. 

The issue you're having is with `sqldbtype`.
It should be the database you are using. Except, only postgres is supported, so it should be `postgres`.
