### ISSUE TITLE
TypeError: Can't instantiate abstract class _Supporters with abstract methods __call__

### ISSUE THREAD

**Issue by xerw** [PaulSonOfLars/tgbot#98]
Hi! This is my first issue.

I am getting error.

> E:\erenay1\tgbot-master>python -m tg_bot
2021-05-07 09:36:27,491 - tg_bot - INFO - Not loading: ['translation', 'rss', 'sed']
2021-05-07 09:36:27,491 - tg_bot - INFO - Modules to load: ['admin', 'afk', 'antiflood', 'backups', 'bans', 'blacklist', 'cust_filters', 'disable', 'global_bans', 'locks', 'log_channel', 'misc', 'msg_deleting', 'muting', 'notes', 'reporting', 'rules', 'userinfo', 'users', 'warns', 'welcome']
Traceback (most recent call last):
  File "C:\Users\Erenay\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Erenay\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\erenay1\tgbot-master\tg_bot\__main__.py", line 74, in <module>
    imported_module = importlib.import_module("tg_bot.modules." + module_name)
  File "C:\Users\Erenay\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\erenay1\tgbot-master\tg_bot\modules\admin.py", line 14, in <module>
    from tg_bot.modules.helper_funcs.extraction import extract_user
  File "E:\erenay1\tgbot-master\tg_bot\modules\helper_funcs\extraction.py", line 7, in <module>
    from tg_bot.modules.users import get_user_id
  File "E:\erenay1\tgbot-master\tg_bot\modules\users.py", line 13, in <module>
    from tg_bot.modules.helper_funcs.filters import CustomFilters
  File "E:\erenay1\tgbot-master\tg_bot\modules\helper_funcs\filters.py", line 7, in <module>
    class CustomFilters(object):
  File "E:\erenay1\tgbot-master\tg_bot\modules\helper_funcs\filters.py", line 12, in CustomFilters
    support_filter = _Supporters()
TypeError: Can't instantiate abstract class _Supporters with abstract methods __call__

Can anyone help me?

**Comment by xerw** [comment]
> Hi, which version of python-telegram-bot are you using? This looks to me like it might be an error to do with the dependencies being imported.
> 
> I would recommend running `pip3 install -r requirements.txt` again to make sure that the right version is installed.

Thanks, the error is solved. I am sorry if I disturbed you.
