### ISSUE TITLE
I am getting error.

### ISSUE THREAD

**Issue by xerw** [PaulSonOfLars/tgbot#99]
Hi!

> 2021-05-07 12:23:10,513 - tg_bot - INFO - Not loading: ['translation', 'rss', 'sed']
2021-05-07 12:23:10,513 - tg_bot - INFO - Modules to load: ['admin', 'afk', 'antiflood', 'backups', 'bans', 'blacklist', 'cust_filters', 'disable', 'global_bans', 'locks', 'log_channel', 'misc', 'msg_deleting', 'muting', 'notes', 'reporting', 'rules', 'userinfo', 'users', 'warns', 'welcome']
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2021-05-07 12:23:12,674 - tg_bot - INFO - Successfully loaded modules: ['admin', 'afk', 'antiflood', 'backups', 'bans', 'blacklist', 'cust_filters', 'disable', 'global_bans', 'locks', 'log_channel', 'misc', 'msg_deleting', 'muting', 'notes', 'reporting', 'rules', 'userinfo', 'users', 'warns', 'welcome']
2021-05-07 12:23:12,675 - tg_bot - INFO - Using long polling.
2021-05-07 12:29:47,945 - telegram.ext.updater - ERROR - unhandled exception in dispatcher
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/ext/updater.py", line 156, in _thread_wrapper
    target(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 228, in start
    self.process_update(update)
  File "/home/pi/tgbot/tg_bot/__main__.py", line 478, in process_update
    cnt = CHATS_CNT.get(update.effective_chat.id, 0)
AttributeError: 'NoneType' object has no attribute 'id'

How I can solve?

**Comment by PaulSonOfLars** [comment]
I don't know what causes this.

Please keep in mind that this repository is EOL, and no longer maintained. Recent telegram updates may have an impact on execution.
